<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-06-22 22:19

=======
# Generated by Django 6.0.6 on 2026-06-22 22:11

import django.db.models.deletion
from django.conf import settings
>>>>>>> c54ecee7ed5c33ae2922d8ed66257e48848ea161
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> c54ecee7ed5c33ae2922d8ed66257e48848ea161
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('f_inicio', models.DateTimeField()),
                ('f_fin', models.DateTimeField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('id_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
>>>>>>> c54ecee7ed5c33ae2922d8ed66257e48848ea161
            ],
        ),
    ]
