# Generated by Django 4.2.30 on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        # El campo id_creador ya quedó integrado en la migración inicial 0001
    ]