# Generated by Django 6.0.6 on 2026-06-23 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='eventos_asistidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
