# Generated by Django 6.0.6 on 2026-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='forum_covers/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reply_images/'),
        ),
    ]
