# Generated by Django 6.0.6 on 2026-06-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_initial'),
        ('forums', '0003_reporte'),
    ]

    operations = [
    ]
